/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-24 at 21:04:27 UTC 
 * Modify at your own risk.
 */

package com.appspot.www_ardux.gentlemeet.model;

/**
 * Model definition for ResourceDevice.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the GentleMeet API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResourceDevice extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("last_sync")
  private String lastSync;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Boolean online;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ResourceCalendar resource;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("resource_id")
  private String resourceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String uuid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("uuid_query")
  private String uuidQuery;

  /**
   * @return value or {@code null} for none
   */
  public String getLastSync() {
    return lastSync;
  }

  /**
   * @param lastSync lastSync or {@code null} for none
   */
  public ResourceDevice setLastSync(String lastSync) {
    this.lastSync = lastSync;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ResourceDevice setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Boolean getOnline() {
    return online;
  }

  /**
   * @param online online or {@code null} for none
   */
  public ResourceDevice setOnline(Boolean online) {
    this.online = online;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ResourceCalendar getResource() {
    return resource;
  }

  /**
   * @param resource resource or {@code null} for none
   */
  public ResourceDevice setResource(ResourceCalendar resource) {
    this.resource = resource;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getResourceId() {
    return resourceId;
  }

  /**
   * @param resourceId resourceId or {@code null} for none
   */
  public ResourceDevice setResourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public ResourceDevice setState(String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public ResourceDevice setType(String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUuid() {
    return uuid;
  }

  /**
   * @param uuid uuid or {@code null} for none
   */
  public ResourceDevice setUuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getUuidQuery() {
    return uuidQuery;
  }

  /**
   * @param uuidQuery uuidQuery or {@code null} for none
   */
  public ResourceDevice setUuidQuery(String uuidQuery) {
    this.uuidQuery = uuidQuery;
    return this;
  }

  @Override
  public ResourceDevice set(String fieldName, Object value) {
    return (ResourceDevice) super.set(fieldName, value);
  }

  @Override
  public ResourceDevice clone() {
    return (ResourceDevice) super.clone();
  }

}
