application: www-ardux
version: v20140530
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- remote_api: on
- appstats: on
- admin_redirect: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: endpoints
  version: "latest"
- name: lxml
  version: "latest"

inbound_services:
- warmup

error_handlers:
  - file: ardux/errors/default_error.html

  - error_code: over_quota
    file: ardux/errors/over_quota.html

  - error_code: dos_api_denial
    file: ardux/errors/dos.html

  - error_code: timeout
    file: ardux/errors/timeout.html

handlers:
- url: /favicon.ico
  static_files: ardux/static/img/favicon.ico
  upload: ardux/static/img/favicon.ico

- url: /robots.txt
  static_files: ardux/static/robots.txt
  upload: ardux/static/robots.txt

- url: /
  static_files: ardux/static/html/landing.html
  upload: ardux/static/html/landing.html

- url: /client/web
  static_files: ardux/static/html/web_client.html
  upload: ardux/static/html/web_client.html

- url: /client/web/checkin
  static_files: ardux/static/html/checkin.html
  upload: ardux/static/html/checkin.html

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /_ah/spi/.*
  script: run.api

- url: /_ah/queue/deferred
  script: run.deferred_app
  login: admin

- url: /admin/static/
  static_dir: lib/flask_admin/static

- url: /static
  static_dir: ardux/static

- url: .*
  script: run.app