application: www-ardux
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.bak
- ^(.*/)?.*/tests/.*
- ^(.*/)?.*/data/.*

handlers:
- url: /_ah/spi/.*
  script: run.api

- url: /_ah/queue/deferred
  script: run.deferred_app
  login: admin

- url: /static
  static_dir: ardux/static

- url: /favicon.ico
  static_files: ardux/static/img/favicon.ico
  upload: ardux/static/img/favicon.ico

- url: .*
  script: run.app