/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-23 at 05:11:53 UTC 
 * Modify at your own risk.
 */

package com.appspot.www_ardux.devices.model;

/**
 * Model definition for ResourceEvent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the devices. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResourceEvent extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> attendees;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("end_date_time")
  private java.lang.String endDateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String organizer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("resource_id")
  private java.lang.String resourceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("resource_key")
  private java.lang.String resourceKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("start_date_time")
  private java.lang.String startDateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String summary;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAttendees() {
    return attendees;
  }

  /**
   * @param attendees attendees or {@code null} for none
   */
  public ResourceEvent setAttendees(java.util.List<java.lang.String> attendees) {
    this.attendees = attendees;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEndDateTime() {
    return endDateTime;
  }

  /**
   * @param endDateTime endDateTime or {@code null} for none
   */
  public ResourceEvent setEndDateTime(java.lang.String endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOrganizer() {
    return organizer;
  }

  /**
   * @param organizer organizer or {@code null} for none
   */
  public ResourceEvent setOrganizer(java.lang.String organizer) {
    this.organizer = organizer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResourceId() {
    return resourceId;
  }

  /**
   * @param resourceId resourceId or {@code null} for none
   */
  public ResourceEvent setResourceId(java.lang.String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResourceKey() {
    return resourceKey;
  }

  /**
   * @param resourceKey resourceKey or {@code null} for none
   */
  public ResourceEvent setResourceKey(java.lang.String resourceKey) {
    this.resourceKey = resourceKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStartDateTime() {
    return startDateTime;
  }

  /**
   * @param startDateTime startDateTime or {@code null} for none
   */
  public ResourceEvent setStartDateTime(java.lang.String startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public ResourceEvent setSummary(java.lang.String summary) {
    this.summary = summary;
    return this;
  }

  @Override
  public ResourceEvent set(String fieldName, Object value) {
    return (ResourceEvent) super.set(fieldName, value);
  }

  @Override
  public ResourceEvent clone() {
    return (ResourceEvent) super.clone();
  }

}
